stages:
  - build
  - checks

build:
  image: golang:1.19
  stage: build
  script: make build

tests:
  image: golang:1.19
  stage: checks
  script: make test
  
lint:
  image: golangci/golangci-lint:v1.42.1
  stage: checks
  script: make lint