stages:
  - checks
  - deploy

build:
  image: golang:1.18
  stage: checks
  script: make build

tests:
  image: golang:1.18
  stage: checks
  script: make tests
  
lint:
  image: golangci/golangci-lint:v1.42.1
  stage: checks
  script: make lint

.prepare_ssh:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa 37.139.42.129 >> ~/.ssh/known_hosts
    - docker login -u iqgroper --password $DOCKER_TOKEN

deploy:
  variables:
    DOCKER_TLS_CERTDIR: ''
  extends: .prepare_ssh
  image: docker
  services:
    - docker:dind
  stage: deploy
  script:
    - docker build -t iqgroper/crudapp-ci-cd:latest .
	  - docker push iqgroper/crudapp-ci-cd:latest
    - ssh ubuntu@37.139.42.129 'sudo docker stop crudapp || echo 1'
    - ssh ubuntu@37.139.42.129 'sudo docker rm crudapp || echo 1'
    - ssh ubuntu@37.139.42.129 'sudo docker pull iqgroper/crudapp-ci-cd:latest'
    - ssh ubuntu@37.139.42.129 'sudo docker run --rm -d -p 8080:8080 --name=crudapp iqgroper/crudapp-ci-cd:latest'
  environment:
    name: prod
    url: http://37.139.42.129
  only:
    - master
    - main