stages:
  - checks
  - deploy

build:
  image: golang:1.18
  stage: checks
  script: make build

tests:
  image: golang:1.18
  stage: checks
  script: make tests
  
lint:
  image: golangci/golangci-lint:v1.42.1
  stage: checks
  script: make lint

.prepare_ssh:
  before_script:
    ##
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use an RPM-based image)
    #
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    #
    #
    # Run ssh-agent (inside the build environment)
    #
    - eval $(ssh-agent -s)
    #
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    # We're using tr to fix line endings which makes ed25519 keys work
    # without extra base64 encoding.
    # https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    #
    - cat $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
    #
    # Create the SSH directory and give it the right permissions
    #
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa 37.139.42.129 >> ~/.ssh/known_hosts
    - docker login --username iqgroper --password $DOCKER_TOKEN

deploy:
  variables:
    DOCKER_TLS_CERTDIR: ''
  extends: .prepare_ssh
  image: docker
  services:
    - docker:dind
  stage: deploy
  script:
    - docker build -t iqgroper/crudapp-ci-cd:latest .
    - docker push iqgroper/crudapp-ci-cd:latest
    - ssh ubuntu@37.139.42.129 'sudo docker stop crudapp || echo 1'
    - ssh ubuntu@37.139.42.129 'sudo docker rm crudapp || echo 1'
    - ssh ubuntu@37.139.42.129 'sudo docker pull iqgroper/crudapp-ci-cd:latest'
    - ssh ubuntu@37.139.42.129 'sudo docker run --rm -d -p 8080:8080 --name=crudapp iqgroper/crudapp-ci-cd:latest'
  environment:
    name: prod
    url: http://37.139.42.129
  only:
    - master
    - main
