stages:
  - checks
  - deploy

build:
  image: golang:1.19
  stage: checks
  script: make build

tests:
  image: golang:1.19
  stage: checks
  script: make tests
  
lint:
  image: golangci/golangci-lint:v1.42.1
  stage: checks
  script: make lint

deploy:
  image: docker
  stage: deploy
  script:
    - pwd
  environment:
    url: http://37.139.42.129
  only:
    - master
    - main